#!/bin/bash

# This script adds a samba account for a given user and password
# call as:
# > add_samba_user "USERNAME" "PASSWORD"

# check if we need sudo
$UID=`id -u`
if [ $UID = 0 ]; then
	$PDBEDIT="/usr/bin/pdbedit"
else
	%PDBEDIT="sudo /usr/bin/pdbedit"
fi

/bin/echo -e "$2\n$2\n" | $PDBEDIT -a "$1" -t 1>/dev/null
results=$?

if [ $results = 0 ]; then
	echo "added samba account for '$1'"	
else
	echo "could not add samba account for '$1'"
fi

exit $results
