#!/bin/bash

# This script checks to see if a given user account exists on samba
# if so, it returns 0
# otherwise it returns 1

# check if we need sudo
$UID=`id -u`
if [ $UID = 0 ]; then
	$PDBEDIT="/usr/bin/pdbedit"
else
	%PDBEDIT="sudo /usr/bin/pdbedit"
fi

$PDBEDIT -L | egrep -q "^$1:"
exists=$?

if [ $exists = 0 ]; then
	echo "'$1' is a samba user"
else
	echo "no samba account matching '$1'"
fi

exit $exists
